[WIP]: osfv integration
Dasharo/osfv-scripts pull request #30
Opened 2024-04-16 13:25 UTC by PLangowski

2024-04-18 15:10 UTC, macpijan requested changes
Looks rather OK. Left one idea on decoupling the RTE module from SnipeIT module, which I think we should consider.

Other than that, I'd ask you to clean up the commits as well.
The merge commit should also not be there.

2024-04-18 15:10 UTC, macpijan commented on osfv_cli/src/osfv/rf/rte_robot.py
> +model_dict = {
I understand why we need it, but I am not happy about it. Let's create an issue to discuss how to get rid of that, perhaps by some naming unification.

2024-04-18 15:10 UTC, macpijan commented on osfv_cli/src/osfv/libs/rte.py
> +                        f"Expected a value for 'sonoff_ip', but got {init_sonoff_ip}"
Second thought:
Isn't it too tightly coupled, the rte module, with snipeit module? How about we **always** expect the SonoffDevice to be initialized outside of this module, and passed in as an argument similarly as the snipeit module? What is more, in this case we probably do not need the snipeit_api inside of the rte module at all?

And depending on our mind, in the CLI or in the robot library, we can create the SonoffDevice based on the IP from command line, or from the SnipeIT.

2024-04-19 10:10 UTC, PLangowski commented on osfv_cli/src/osfv/libs/rte.py
> +                        f"Expected a value for 'sonoff_ip', but got {init_sonoff_ip}"
It now prints 'None' directly 2bd76756461401bad092460dc24146b55cb8fa08

2024-04-19 10:10 UTC, PLangowski commented on osfv_cli/src/osfv/libs/rte.py
> +                return SonoffDevice(init_sonoff_ip), init_sonoff_ip
2bd76756461401bad092460dc24146b55cb8fa08

2024-04-19 10:11 UTC, PLangowski commented on osfv_cli/src/osfv/libs/rte.py
>              sonoff_ip = self.snipeit_api.get_sonoff_ip_by_rte_ip(self.rte_ip)
yes, that is what we want here

2024-04-19 10:11 UTC, PLangowski commented on osfv_cli/src/osfv/rf/rte_robot.py
> +            raise TypeError(f"Expected a value for 'config', but got {osfv_model}")
2bd76756461401bad092460dc24146b55cb8fa08

2024-04-19 10:21 UTC, PLangowski commented on osfv_cli/src/osfv/libs/rte.py
> +                        f"Expected a value for 'sonoff_ip', but got {init_sonoff_ip}"
We then need to move this function somewhere else. As you said, both RTERobot and the CLI will need to initialize the SonoffDevice. So those 2 modules would then be coupled as well, because we probably only want this function in one of them and the other one will need to import it.

2024-04-19 13:09 UTC, PLangowski commented on osfv_cli/src/osfv/libs/rte.py
> +                        f"Expected a value for 'sonoff_ip', but got {init_sonoff_ip}"
One potential solution would be to create some kind of utils script, which will hold this function (and future ones that will suffer from the same problem)

2024-04-22 06:27 UTC, PLangowski commented on osfv_cli/src/osfv/libs/rte.py
> +                        f"Expected a value for 'sonoff_ip', but got {init_sonoff_ip}"
@macpijan Regarding the solution mentioned above, you can take a look at https://github.com/Dasharo/osfv-scripts/pull/31 to see if you like that idea. It's not the whole solution (the cli will need changing as well), but it shows the concept.

2024-04-22 20:37 UTC, macpijan commented on osfv_cli/src/osfv/libs/rte.py
> +                        f"Expected a value for 'sonoff_ip', but got {init_sonoff_ip}"
The `CLI` or `RobotRTE` are one layer higher, so this is fine if they need to integrate all of the libraries, like snipeit, sonoff, etc. But if we can avoid the usage of snipeit inside RTE, that would be good. Proposed solution makes sense, let's try to continue.

2024-04-22 20:38 UTC, macpijan commented on osfv_cli/src/osfv/rf/rte_robot.py
> +model_dict = {
Please link issue once it is created

2024-04-23 07:22 UTC, PLangowski commented on osfv_cli/src/osfv/libs/rte.py
> +                        f"Expected a value for 'sonoff_ip', but got {init_sonoff_ip}"
I integrated the changes here f9c6bd54a4256d453c43a8a5a4ccc2fb3c2fffc6

2024-04-23 07:30 UTC, PLangowski commented on osfv_cli/src/osfv/rf/rte_robot.py
> +model_dict = {
https://github.com/Dasharo/osfv-scripts/issues/32

2024-04-24 06:28 UTC, macpijan commented on osfv_cli/src/osfv/libs/rte.py
> +                        f"Expected a value for 'sonoff_ip', but got {init_sonoff_ip}"
looks fine, thanks

2024-04-24 06:28 UTC, macpijan commented on osfv_cli/src/osfv/rf/rte_robot.py
> +model_dict = {
Thanks

2024-04-24 06:32 UTC, macpijan reviewed
@PLangowski Code looks OK, but we still need to:
- [ ] cleanup commits - we specifically do not want to merge commits like `wip`, or `refactor, if possible; we should split the whole changes into a few logical commits
- [ ] pre-commit fails, possibly you do not have it installed locally in this repo?

2024-04-25 08:11 UTC, PLangowski commented
@macpijan I cleaned up the commits.

2024-06-11 18:45 UTC, merged