osfv_cli/src/osfv: Fix success message on flashing fail
Dasharo/osfv-scripts pull request #62
Opened 2024-09-05 12:43 UTC by SebastianCzapla

2024-09-05 13:07 UTC, SebastianCzapla commented
Fix for: https://github.com/Dasharo/osfv-scripts/issues/41

2024-09-05 14:24 UTC, miczyg1 requested changes
Just to be precise

2024-09-05 14:24 UTC, miczyg1 commented on osfv_cli/src/osfv/cli/cli.py
> +        print(f"Flash written")
```suggestion
        print(f"Flash written successfully")
```

2024-09-05 14:24 UTC, miczyg1 commented on osfv_cli/src/osfv/rf/rte_robot.py
> +            robot.api.logger.info(f"Flash written")
```suggestion
            robot.api.logger.info(f"Flash written successfully")
```

2024-09-05 14:29 UTC, SebastianCzapla commented on osfv_cli/src/osfv/rf/rte_robot.py
> +            robot.api.logger.info(f"Flash written")
Changed commit to match suggested messages.

2024-09-06 07:11 UTC, miczyg1 approved these changes

2024-09-06 07:11 UTC, merged